title: We'll make Jekyll great again!
author: RD@Rieger-Design
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  What a awesome description for my new site here. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
